# Site settings
title: Bradley Rosenfeld
email: thatguy@bradleyrosenfeld.com
description: I'm a computer scientist who believes that pixels are people too
baseurl: ""
url: "https://bradleyrosenfeld.com"

# Plugins
gems:
  - octopress-minify-html
  - octopress-autoprefixer

# Build settings
markdown: kramdown
sass:
    style: compressed
minify_html: true
exclude: 
  - Gemfile
  - Gemfile.lock
  - README.md

ga-id: "UA-39603531-1424"