# Site settings
title: Bradley Rosenfeld
email: thatguy@bradleyrosenfeld.com
description: Hi, I'm Bradley and I break computers.
baseurl: ""
url: "https://bradleyrosenfeld.com"

# Plugins
gems:
  - octopress-minify-html
  - octopress-autoprefixer

# Build settings
markdown: kramdown
sass:
    style: compressed
minify_html: true
exclude: 
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
